import React, { createContext, useContext, useState } from 'react';

type Language = 'ru' | 'kk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    dashboard: "Дашборд",
    createQuiz: "Создать тест",
    favorites: "Избранное",
    logout: "Выйти",
    welcome: "Добро пожаловать",
    guestMode: "Гостевой режим",
    register: "Зарегистрироваться",
    myQuizzes: "Мои тесты",
    noQuizzes: "У вас пока нет тестов.",
    startCreating: "Начните создавать!",
    quizTitle: "Название теста",
    questionsCount: "вопросов",
    start: "Начать",
    edit: "Изменить",
    delete: "Удалить",
    setupQuiz: "Настройка теста",
    randomizeQuestions: "Перемешать вопросы",
    randomizeAnswers: "Перемешать ответы",
    mode: "Режим",
    practice: "Тренировка",
    exam: "Экзамен",
    timer: "Таймер (мин)",
    startTest: "Начать тест",
    results: "Результаты",
    score: "Счет",
    correctAnswers: "Верных ответов",
    retakeMistakes: "Работа над ошибками",
    retakeAll: "Пересдать всё",
    goHome: "На главную",
    exit: "Выйти из теста",
    back: "Назад",
    next: "Далее",
    finish: "Завершить",
    progress: "Прогресс",
    question: "Вопрос",
    outOf: "из",
    noQuestionsFound: "Вопросов не найдено",
    congratsNoMistakes: "Поздравляем! Похоже, в этом тесте у вас больше нет неверных ответов.",
    chooseRange: "Выберите участок теста",
    allQuestions: "Все вопросы",
    autoFindAnswers: "Auto-AI: Найти ответы",
    aiDescription: "ИИ автоматически выделит верный вариант",
    recognizeQuestions: "Распознать вопросы",
    pasteText: "Вставьте текст теста сюда...",
    platonusAi: "Platonus AI",
    authChecking: "Загрузка данных...",
    availableQuizzes: "Доступные тесты",
    timesSolved: "Решено раз",
    deleteConfirmTitle: "Вы уверены?",
    deleteConfirmDesc: "Это действие нельзя отменить. Тест будет удален навсегда.",
    cancel: "Отмена",
    order: "Порядок",
    practiceDesc: "Показывает правильный ответ сразу после выбора.",
    examDesc: "Результат и ошибки только в конце теста.",
    timerLimit: "Ограничение времени (минуты)",
    timerDesc: "0 = без ограничений",
    bestScore: "Рекорд",
    attemptsCount: "Попыток",
    resultPerfect: "Идеально! Вы мастер! 🎉",
    resultGood: "Отличный результат! 🌟",
    resultAverage: "Неплохо, но можно лучше 👍",
    resultBad: "Попробуйте еще раз, у вас получится! 💪",
    resultNotFound: "Результат не найден",
    createNewQuiz: "Создание нового теста",
    manualInput: "Ручной ввод",
    fileUpload: "Загрузка файла",
    preview: "Предпросмотр",
    clearAll: "Очистить всё",
    saveQuiz: "Сохранить тест",
    limitReached: "Лимит исчерпан",
    processing: "Обработка",
    correct: "Верный",
    activation: "Активация доступа",
    invitationEntry: "Вход по приглашению",
    enterNameDesc: "Введите ваше имя для активации доступа по приглашению.",
    enterTokenDesc: "Вставьте код приглашения, который вы получили, и введите ваше имя.",
    tokenLabel: "Код приглашения (Токен)",
    nameLabel: "Ваше Имя",
    activating: "Активация...",
    registerButton: "Зарегистрироваться",
    fillAllFields: "Пожалуйста, заполните все поля.",
    registerError: "Ошибка регистрации. Проверьте правильность токена.",
    favoritesEmpty: "Список избранного пуст",
    favoritesEmptyDesc: "Добавляйте сложные вопросы в избранное во время прохождения тестов, чтобы повторить их здесь.",
    favoriteQuestions: "Избранные вопросы",
    selectedQuestions: "Выбрано вопросов",
    removeExcessDesc: "Удалите лишние перед началом.",
    questionsList: "Список вопросов",
    clickTrashDesc: "Нажмите на значок корзины, чтобы убрать вопрос из этого списка.",
    runTest: "Запустить тест",
    totalQuestionsLabel: "Всего вопросов",
    appName: "Platonus Test",
    changeTheme: "Сменить тему",
    account: "Аккаунт",
    quizNotFound: "Тест не найден",
    guestLimitDesc: "Пожалуйста, зарегистрируйтесь, чтобы продолжить.",
    mistakesMode: "Режим работы над ошибками",
    errorCreatingQuiz: "Ошибка при создании теста.",
    errorParsing: "Ошибка разбора текста.",
    errorUnsupportedFormat: "Формат не поддерживается. Используйте .docx, .doc или .txt",
    errorFileRead: "Ошибка при чтении файла.",
    errorSave: "Ошибка при сохранении.",
    errorAi: "Ошибка ИИ.",
    guestLimitQuestions: "Лимит гостя: 300 вопросов.",
    guestLimitInfo: "Вы находитесь в гостевом режиме. Зарегистрируйтесь, чтобы сохранять результаты и создавать больше тестов.",
    success: "Успех",
    error: "Ошибка",
    adminDashboard: "Панель администратора",
    generateToken: "Создать Invite Token",
    totalUsers: "Всего пользователей",
    usedTokens: "Использовано токенов",
    freeTokens: "Свободные токены",
    latestTokens: "Последние токены",
    usersTimeline: "Пользователи (Хронология)",
    registeredAt: "Зарегистрирован",
    deleteToken: "Удалить токен",
    deleteUser: "Удалить пользователя",
    tokenCreated: "Токен создан!",
    errorGeneratingToken: "Ошибка при создании токена",
    deleteConfirm: "Вы уверены, что хотите удалить эту запись?",
    errorDeleting: "Ошибка при удалении (возможно, есть связанные данные)",
    copyLink: "Копировать ссылку",
    used: "Использовано",
    active: "Активен",
    usedBy: "Кем использован",
  },
  kk: {
    dashboard: "Басты бет",
    createQuiz: "Тест жасау",
    favorites: "Таңдаулылар",
    logout: "Шығу",
    welcome: "Қош келдіңіз",
    guestMode: "Қонақ режимі",
    register: "Тіркелу",
    myQuizzes: "Менің тесттерім",
    noQuizzes: "Сізде әлі тесттер жоқ.",
    startCreating: "Бастаңыз!",
    quizTitle: "Тест атауы",
    questionsCount: "сұрақ",
    start: "Бастау",
    edit: "Өзгерту",
    delete: "Өшіру",
    setupQuiz: "Тестті баптау",
    randomizeQuestions: "Сұрақтарды араластыру",
    randomizeAnswers: "Жауаптарды араластыру",
    mode: "Режим",
    practice: "Жаттығу",
    exam: "Емтихан",
    timer: "Таймер (мин)",
    startTest: "Тестті бастау",
    results: "Нәтижелер",
    score: "Ұпай",
    correctAnswers: "Дұрыс жауаптар",
    retakeMistakes: "Қателермен жұмыс",
    retakeAll: "Қайта тапсыру",
    goHome: "Басты бетке",
    exit: "Тесттен шығу",
    back: "Артқа",
    next: "Келесі",
    finish: "Аяқтау",
    progress: "Прогресс",
    question: "Сұрақ",
    outOf: "ішінен",
    noQuestionsFound: "Сұрақтар табылмады",
    congratsNoMistakes: "Құттықтаймыз! Бұл тестте сізде қате жауаптар қалмаған сияқты.",
    chooseRange: "Тест бөлімін таңдаңыз",
    allQuestions: "Барлық сұрақтар",
    autoFindAnswers: "Auto-AI: Жауаптарды табу",
    aiDescription: "ИИ дұрыс нұсқаны автоматты түрде белгілейді",
    recognizeQuestions: "Сұрақтарды тану",
    pasteText: "Тест мәтінін осы жерге қойыңыз...",
    platonusAi: "Platonus AI",
    authChecking: "Деректер жүктелуде...",
    availableQuizzes: "Қолжетімді тесттер",
    timesSolved: "Тапсырылған саны",
    deleteConfirmTitle: "Сенімдісіз бе?",
    deleteConfirmDesc: "Бұл әрекетті болдырмау мүмкін емес. Тест біржола жойылады.",
    cancel: "Болдырмау",
    order: "Тәртіп",
    practiceDesc: "Дұрыс жауапты таңдағаннан кейін бірден көрсетеді.",
    examDesc: "Нәтиже мен қателер тек тест соңында көрсетіледі.",
    timerLimit: "Уақыт шектеуі (минут)",
    timerDesc: "0 = шектеусіз",
    bestScore: "Рекорд",
    attemptsCount: "Талпыныстар",
    resultPerfect: "Керемет! Сіз шеберсіз! 🎉",
    resultGood: "Өте жақсы нәтиже! 🌟",
    resultAverage: "Жаман емес, бірақ жақсартуға болады 👍",
    resultBad: "Тағы да көріңіз, қолыңыздан келеді! 💪",
    resultNotFound: "Нәтиже табылмады",
    createNewQuiz: "Жаңа тест жасау",
    manualInput: "Қолмен енгізу",
    fileUpload: "Файлды жүктеу",
    preview: "Алдын ала қарау",
    clearAll: "Барлығын тазалау",
    saveQuiz: "Тестті сақтау",
    limitReached: "Шектеуге жеттіңіз",
    processing: "Өңдеу",
    correct: "Дұрыс",
    activation: "Кіруді белсендіру",
    invitationEntry: "Шақыру арқылы кіру",
    enterNameDesc: "Шақыру арқылы кіруді белсендіру үшін атыңызды енгізіңіз.",
    enterTokenDesc: "Алған шақыру кодын қойып, атыңызды енгізіңіз.",
    tokenLabel: "Шақыру коды (Токен)",
    nameLabel: "Сіздің атыңыз",
    activating: "Белсендіру...",
    registerButton: "Тіркелу",
    fillAllFields: "Барлық өрістерді толтырыңыз.",
    registerError: "Тіркелу қатесі. Токеннің дұрыстығын тексеріңіз.",
    favoritesEmpty: "Таңдаулылар тізімі бос",
    favoritesEmptyDesc: "Тест тапсыру кезінде күрделі сұрақтарды осында қайталау үшін таңдаулыларға қосыңыз.",
    favoriteQuestions: "Таңдаулы сұрақтар",
    selectedQuestions: "Таңдалған сұрақтар",
    removeExcessDesc: "Бастамас бұрын артықтарын өшіріңіз.",
    questionsList: "Сұрақтар тізімі",
    clickTrashDesc: "Сұрақты бұл тізімнен шығару үшін себет белгішесін басыңыз.",
    runTest: "Тестті бастау",
    totalQuestionsLabel: "Барлық сұрақтар",
    appName: "Platonus Test",
    changeTheme: "Тақырыпты өзгерту",
    account: "Аккаунт",
    quizNotFound: "Тест табылмады",
    guestLimitDesc: "Жалғастыру үшін тіркеліңіз.",
    mistakesMode: "Қателермен жұмыс режимі",
    errorCreatingQuiz: "Тест жасау кезінде қате кетті.",
    errorParsing: "Мәтінді талдау қатесі.",
    errorUnsupportedFormat: "Формат қолдау көрсетілмейді. .docx, .doc немесе .txt қолданыңыз",
    errorFileRead: "Файлды оқу қатесі.",
    errorSave: "Сақтау қатесі.",
    errorAi: "ИИ қатесі.",
    guestLimitQuestions: "Қонақ шектеуі: 300 сұрақ.",
    guestLimitInfo: "Сіз қонақ режиміндесіз. Нәтижелерді сақтау және көбірек тест жасау үшін тіркеліңіз.",
    success: "Сәтті",
    error: "Қате",
    adminDashboard: "Әкімші панелі",
    generateToken: "Шақыру токенін жасау",
    totalUsers: "Барлық пайдаланушылар",
    usedTokens: "Пайдаланылған токендер",
    freeTokens: "Бос токендер",
    latestTokens: "Соңғы токендер",
    usersTimeline: "Пайдаланушылар (Хронология)",
    registeredAt: "Тіркелді",
    deleteToken: "Токенді өшіру",
    deleteUser: "Пайдаланушыны өшіру",
    tokenCreated: "Токен жасалды!",
    errorGeneratingToken: "Токен жасау қатесі",
    deleteConfirm: "Бұл жазбаны өшіруге сенімдісіз бе?",
    errorDeleting: "Өшіру қатесі (мүмкін, байланысты деректер бар)",
    copyLink: "Сілтемені көшіру",
    used: "Пайдаланылды",
    active: "Белсенді",
    usedBy: "Кім пайдаланды",
  },
  en: {
    dashboard: "Dashboard",
    createQuiz: "Create Quiz",
    favorites: "Favorites",
    logout: "Logout",
    welcome: "Welcome",
    guestMode: "Guest Mode",
    register: "Register",
    myQuizzes: "My Quizzes",
    noQuizzes: "You don't have any quizzes yet.",
    startCreating: "Start creating!",
    quizTitle: "Quiz Title",
    questionsCount: "questions",
    start: "Start",
    edit: "Edit",
    delete: "Delete",
    setupQuiz: "Quiz Setup",
    randomizeQuestions: "Randomize Questions",
    randomizeAnswers: "Randomize Answers",
    mode: "Mode",
    practice: "Practice",
    exam: "Exam",
    timer: "Timer (min)",
    startTest: "Start Test",
    results: "Results",
    score: "Score",
    correctAnswers: "Correct Answers",
    retakeMistakes: "Work on Mistakes",
    retakeAll: "Retake All",
    goHome: "Go Home",
    exit: "Exit Test",
    back: "Back",
    next: "Next",
    finish: "Finish",
    progress: "Progress",
    question: "Question",
    outOf: "out of",
    noQuestionsFound: "No questions found",
    congratsNoMistakes: "Congratulations! It seems you have no more incorrect answers in this quiz.",
    chooseRange: "Choose Question Range",
    allQuestions: "All Questions",
    autoFindAnswers: "Auto-AI: Find Answers",
    aiDescription: "AI will automatically highlight the correct variant",
    recognizeQuestions: "Recognize Questions",
    pasteText: "Paste quiz text here...",
    platonusAi: "Platonus AI",
    authChecking: "Loading data...",
    availableQuizzes: "Available Quizzes",
    timesSolved: "Times solved",
    deleteConfirmTitle: "Are you sure?",
    deleteConfirmDesc: "This action cannot be undone. The quiz will be permanently deleted.",
    cancel: "Cancel",
    order: "Order",
    practiceDesc: "Shows the correct answer immediately after selection.",
    examDesc: "Results and errors are shown only at the end of the test.",
    timerLimit: "Time limit (minutes)",
    timerDesc: "0 = no limit",
    bestScore: "Best Score",
    attemptsCount: "Attempts",
    resultPerfect: "Perfect! You are a master! 🎉",
    resultGood: "Great result! 🌟",
    resultAverage: "Not bad, but could be better 👍",
    resultBad: "Try again, you can do it! 💪",
    resultNotFound: "Result not found",
    createNewQuiz: "Create New Quiz",
    manualInput: "Manual Input",
    fileUpload: "File Upload",
    preview: "Preview",
    clearAll: "Clear All",
    saveQuiz: "Save Quiz",
    limitReached: "Limit Reached",
    processing: "Processing",
    correct: "Correct",
    activation: "Access Activation",
    invitationEntry: "Enter by Invitation",
    enterNameDesc: "Enter your name to activate access via invitation.",
    enterTokenDesc: "Paste the invitation code you received and enter your name.",
    tokenLabel: "Invitation Code (Token)",
    nameLabel: "Your Name",
    activating: "Activating...",
    registerButton: "Register",
    fillAllFields: "Please fill in all fields.",
    registerError: "Registration error. Check the token validity.",
    favoritesEmpty: "Favorites list is empty",
    favoritesEmptyDesc: "Add difficult questions to favorites during tests to repeat them here.",
    favoriteQuestions: "Favorite Questions",
    selectedQuestions: "Questions selected",
    removeExcessDesc: "Remove excess questions before starting.",
    questionsList: "Questions List",
    clickTrashDesc: "Click the trash icon to remove a question from this list.",
    runTest: "Run Test",
    totalQuestionsLabel: "Total questions",
    appName: "Platonus Test",
    changeTheme: "Change theme",
    account: "Account",
    quizNotFound: "Quiz not found",
    guestLimitDesc: "Please register to continue.",
    mistakesMode: "Mistakes mode",
    errorCreatingQuiz: "Error creating quiz.",
    errorParsing: "Parsing error.",
    errorUnsupportedFormat: "Format not supported. Use .docx, .doc or .txt",
    errorFileRead: "File read error.",
    errorSave: "Save error.",
    errorAi: "AI Error.",
    guestLimitQuestions: "Guest limit: 300 questions.",
    guestLimitInfo: "You are in guest mode. Register to save results and create more quizzes.",
    success: "Success",
    error: "Error",
    adminDashboard: "Admin Dashboard",
    generateToken: "Generate Invite Token",
    totalUsers: "Total Users",
    usedTokens: "Used Tokens",
    freeTokens: "Free Tokens",
    latestTokens: "Latest Tokens",
    usersTimeline: "Users Timeline",
    registeredAt: "Registered",
    deleteToken: "Delete Token",
    deleteUser: "Delete User",
    tokenCreated: "Token created!",
    errorGeneratingToken: "Error generating token",
    deleteConfirm: "Are you sure you want to delete this record?",
    errorDeleting: "Error deleting (possible related data)",
    copyLink: "Copy Link",
    used: "Used",
    active: "Active",
    usedBy: "Used By",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'ru';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string) => {
    const dict = translations[language] as any;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
